import "../globals.css";
import NavBar  from "./conponents/NavBar/NavBar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icon: '/favicon.ico',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <NavBar />
        {children}
    </>
  )
}