import "../globals.css";
import NavBar  from "../../components/NavBar/NavBar";
import axios from "axios";
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icon: '/favicon.ico',
}

const checkauth = async (endpoint : string) => {
    const cookieStore = cookies();
    const token = cookieStore.get('access_token');

    if (!token)
      return null;
  
    const res = await fetch(endpoint, {'headers' : {'cookie' : `access_token=${token.value}`}});

    if (res.status === 200) {
      return res.json();
    }
      
    return null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const isAuth = await checkauth('http://localhost:8000/auth/isAuth');
  if (!isAuth)
    redirect('/');
  
  return (
    <>
        <NavBar />
        {children}
    </>
  )
}