import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icon: '/favicon.ico',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="h-full w-full" lang="en">
      <body className="h-full w-full text-center">
        {children}
      </body>
    </html>
  )
}