import React from 'react'

import Fact2AuthForm from '@/components/fact2Auth/Fact2AuthForm'

const Fact2Auth = async() => {
  return (
    <main className="h-full grid place-content-center  text-base">
        <section className="flex flex-col items-center bg-light-gray/60 rounded-[50px] py-[5.5rem] px-[2.25rem]
                    md:py-[5rem] md:px-[5.25rem] lg:px-[9rem] lg:py-[7.25rem] ">
          <h1 className="text-3xl font-bold text-center text-blue mb-10">tow factor authentication</h1>
          <p className='max-w-[400px] mb-8' >confirm your identity by entering the authentication code generated by your authenticator app</p>
          <Fact2AuthForm />
        </section>
    </main>
  )
}

export default Fact2Auth;